### ISSUE TITLE
[Documentation] Consider adding "copy/paste" installation instructions for platforms?

### ISSUE THREAD

**Issue by jleaders** [apposed/jgo#14]
Your tool is great, thank you!

Perhaps this is too explicit/specific, but, in lieu of adding *.deb +  PPA for ubuntu (the "proper" way) or at least these "copy / paste" install instructions to the readme for Linux/OSX users to make adoption easier:
Creates jrun binary in user's home bin:
```
mkdir ~/bin
cd ~/bin
git clone https://github.com/ctrueden/jrun 
sudo ln -s ~/bin/jrun/jrun /usr/bin/   
jrun --help       
```

**Comment by ctrueden** [comment]
Sorry for the delay in reply, @jleaders, and thanks for the suggestion!

As an aside, if you want to symlink a program system-wide, I'd suggest `/opt/bin` or `/usr/local/bin` (depending on the platform) rather than `/usr/bin`, since the latter is normally reserved only for stuff installed by the package manager.

I added some sample commands to the README for installing `jrun` into `~/bin`.
